export const BLOCK_TEMPLATES = [
  {
    type: 'hero',
    label: 'Bienvenida',
    icon: '🌟',
    description: 'Encabezado con título, subtítulo y botón',
    defaults: {
      title: 'Bienvenida a mi espacio',
      subtitle: 'Un lugar seguro para tu bienestar emocional',
      buttonText: 'Agenda tu consulta',
      buttonLink: '#',
      bgColor: '#f5f0ff',
      textColor: '#3b1f6e',
      image: '',
    },
  },
  {
    type: 'about',
    label: 'Sobre mí',
    icon: '👤',
    description: 'Presentación personal con texto e imagen',
    defaults: {
      title: 'Sobre mí',
      body: 'Escribe aquí tu presentación...',
      bgColor: '#ffffff',
      textColor: '#2d2d2d',
      accentColor: '#7c3aed',
      image: '',
    },
  },
  {
    type: 'services',
    label: 'Servicios',
    icon: '📋',
    description: 'Tarjetas con los servicios que ofrecés',
    defaults: {
      title: 'Mis servicios',
      bgColor: '#faf7ff',
      textColor: '#2d2d2d',
      accentColor: '#7c3aed',
      cards: [
        { id: `s${Date.now()}`, title: 'Nuevo servicio', description: 'Descripción del servicio.', icon: '⭐' },
      ],
    },
  },
  {
    type: 'pricing',
    label: 'Precios',
    icon: '💰',
    description: 'Tabla de planes y tarifas',
    defaults: {
      title: 'Planes y Tarifas',
      subtitle: 'Elige el plan que mejor se adapte a tus necesidades',
      bgColor: '#ffffff',
      textColor: '#2d2d2d',
      accentColor: '#7c3aed',
      plans: [
        {
          id: `plan${Date.now()}a`,
          name: 'Sesión individual',
          description: 'Para comenzar tu proceso',
          currency: 'Q',
          price: '250',
          period: 'por sesión',
          featured: false,
          buttonText: 'Reservar',
          buttonLink: '#contacto',
          features: [
            { id: 'f1a', text: 'Sesión de 50 minutos', included: true },
            { id: 'f2a', text: 'Evaluación inicial', included: true },
            { id: 'f3a', text: 'Seguimiento por WhatsApp', included: false },
          ],
        },
        {
          id: `plan${Date.now()}b`,
          name: 'Paquete mensual',
          description: 'Proceso terapéutico continuo',
          currency: 'Q',
          price: '900',
          period: '4 sesiones / mes',
          featured: true,
          buttonText: 'Comenzar ahora',
          buttonLink: '#contacto',
          features: [
            { id: 'f1b', text: 'Sesión de 50 minutos', included: true },
            { id: 'f2b', text: 'Evaluación inicial', included: true },
            { id: 'f3b', text: 'Seguimiento por WhatsApp', included: true },
          ],
        },
      ],
    },
  },
]
