export const BLOCK_TEMPLATES = [
  {
    type: 'hero',
    label: 'Bienvenida',
    icon: '🌟',
    description: 'Encabezado con título, subtítulo y botón',
    defaults: {
      title: 'Bienvenida a mi espacio',
      subtitle: 'Un lugar seguro para tu bienestar emocional',
      buttonText: 'Agenda tu consulta',
      buttonLink: '#',
      bgColor: '#f0faf8',
      textColor: '#3b1f6e',
      image: '',
      imageFocalX: 50,
      imageFocalY: 50,
      imageZoom: 1,
      textAlign: 'center',
      fontFamily: 'Inter, sans-serif',
      blockAnimation: 'none',
      textEntrance: 'none',
      ambientBg: 'none',
      ambientColor1: '#5BB8A8',
      ambientColor2: '#a8e6df',
      ambientIntensity: 0.3,
    },
  },
  {
    type: 'about',
    label: 'Sobre mí',
    icon: '👤',
    description: 'Presentación personal con texto e imagen',
    defaults: {
      title: 'Sobre mí',
      body: 'Escribe aquí tu presentación...',
      bgColor: '#ffffff',
      textColor: '#2d2d2d',
      accentColor: '#5BB8A8',
      image: '',
      imageFocalX: 50,
      imageFocalY: 50,
      imageZoom: 1,
      textAlign: 'left',
      fontFamily: 'Inter, sans-serif',
      blockAnimation: 'none',
    },
  },
  {
    type: 'services',
    label: 'Servicios',
    icon: '📋',
    description: 'Tarjetas con los servicios que ofrecés',
    defaults: {
      title: 'Mis servicios',
      bgColor: '#f4faf9',
      textColor: '#2d2d2d',
      accentColor: '#5BB8A8',
      fontFamily: 'Inter, sans-serif',
      blockAnimation: 'none',
      cardAnimation: 'none',
      cards: [
        { id: `s${Date.now()}`, title: 'Nuevo servicio', description: 'Descripción del servicio.', icon: '⭐', textAlign: 'left' },
      ],
    },
  },
  {
    type: 'pricing',
    label: 'Precios',
    icon: '💰',
    description: 'Tabla de planes y tarifas',
    defaults: {
      title: 'Planes y Tarifas',
      subtitle: 'Elige el plan que mejor se adapte a tus necesidades',
      bgColor: '#ffffff',
      textColor: '#2d2d2d',
      accentColor: '#5BB8A8',
      blockAnimation: 'none',
      plans: [
        {
          id: `plan${Date.now()}a`,
          name: 'Sesión individual',
          description: 'Para comenzar tu proceso',
          currency: 'Q',
          price: '250',
          period: 'por sesión',
          featured: false,
          buttonText: 'Reservar',
          buttonLink: '#contacto',
          features: [
            { id: 'f1a', text: 'Sesión de 50 minutos', included: true },
            { id: 'f2a', text: 'Evaluación inicial', included: true },
            { id: 'f3a', text: 'Seguimiento por WhatsApp', included: false },
          ],
        },
        {
          id: `plan${Date.now()}b`,
          name: 'Paquete mensual',
          description: 'Proceso terapéutico continuo',
          currency: 'Q',
          price: '900',
          period: '4 sesiones / mes',
          featured: true,
          buttonText: 'Comenzar ahora',
          buttonLink: '#contacto',
          features: [
            { id: 'f1b', text: 'Sesión de 50 minutos', included: true },
            { id: 'f2b', text: 'Evaluación inicial', included: true },
            { id: 'f3b', text: 'Seguimiento por WhatsApp', included: true },
          ],
        },
      ],
    },
  },
  {
    type: 'books',
    label: 'Libros recomendados',
    icon: '📚',
    description: 'Grid de portadas con título, autor y descripción',
    defaults: {
      title: 'Libros recomendados',
      subtitle: 'Recursos que han transformado mi práctica',
      bgColor: '#f4faf9',
      textColor: '#2d2d2d',
      accentColor: '#5BB8A8',
      blockAnimation: 'none',
      books: [
        {
          id: `b${Date.now()}`,
          title: 'El cuerpo lleva la cuenta',
          author: 'Bessel van der Kolk',
          description: 'Un libro fundamental sobre el trauma y cómo el cuerpo lo almacena.',
          image: '',
          link: '',
        },
      ],
    },
  },
  {
    type: 'academic',
    label: 'Historial Académico',
    icon: '🎓',
    description: 'Línea de tiempo con títulos, certificaciones y logros',
    defaults: {
      title: 'Historial Académico',
      subtitle: 'Formación y certificaciones',
      bgColor: '#ffffff',
      textColor: '#2d2d2d',
      accentColor: '#5BB8A8',
      blockAnimation: 'none',
      items: [
        { id: 'ac1', type: 'degree', title: 'Licenciatura en Psicología', institution: 'Universidad de San Carlos de Guatemala', year: '2018', description: '' },
        { id: 'ac2', type: 'certification', title: 'Certificación en Primeros Auxilios Psicológicos', institution: 'AGAPI Guatemala', year: '2020', description: '' },
      ],
    },
  },
  {
    type: 'location',
    label: 'Ubicación',
    icon: '📍',
    description: 'Dirección, horarios y mapa de Google',
    defaults: {
      title: 'Mi Consultorio',
      subtitle: 'Encuentra un espacio seguro cerca a ti',
      bgColor: '#ffffff',
      textColor: '#2d2d2d',
      accentColor: '#5BB8A8',
      blockAnimation: 'none',
      address: '',
      mapUrl: '',
      mapsLink: '',
      buttonText: 'Cómo llegar',
      phone: '',
      email: '',
      hours: [
        { id: 'h1', days: 'Lunes – Viernes', time: '9:00 – 18:00' },
        { id: 'h2', days: 'Sábado', time: '9:00 – 13:00' },
      ],
    },
  },
  {
    type: 'carousel',
    label: 'Carrusel de fotos',
    icon: '🖼️',
    description: 'Galería deslizable de imágenes',
    defaults: {
      title: '',
      subtitle: '',
      bgColor: '#ffffff',
      textColor: '#2d2d2d',
      accentColor: '#5BB8A8',
      blockAnimation: 'none',
      autoPlay: true,
      interval: 4,
      height: '480px',
      photos: [],
    },
  },
  {
    type: 'podcast',
    label: 'Podcast',
    icon: '🎙️',
    description: 'Plataformas de escucha y lista de episodios',
    defaults: {
      title: 'Mi Podcast',
      subtitle: 'Conversaciones sobre bienestar emocional y salud mental',
      bgColor: '#f0faf8',
      textColor: '#2d2d2d',
      accentColor: '#5BB8A8',
      blockAnimation: 'none',
      platforms: { spotify: '', apple: '', youtube: '', google: '' },
      episodes: [],
    },
  },
]
